Implementation of delete.C
Summon528/UW-564-Stage6 pull request #5
Opened 2022-12-09 04:15 UTC by chrisknguyen1010

2022-12-09 17:23 UTC, WalterLu3 commented
Did you test it on your end? Please make sure it compiles. Also, you need to run clang-format to pass the github test.

2022-12-09 21:16 UTC, chrisknguyen1010 commented
Not sure what the error is referencing. Is it coming from clang or from my code?

2022-12-09 21:41 UTC, Summon528 commented
Seems like a new version of clang-tidy breaks the action. I've reverted that can you merge the master branch and try again?

2022-12-10 00:38 UTC, WalterLu3 commented
It now successfully compiles, but the output of your code is not the same as the one provided by the instructor. Have you checked that? You can inspect the output by running
`qutest 7`
on your end.

This above line of code runs the qu.7 which is the query related to the delete method.

The correct output of qu.7 can be found under the file section of the Canvas. I usually test the code on cs machines first, since it is how they test our code.

Also, I suggest in the future you look at the result of the github test. It provides important information about things that might go wrong in your code. You can see that it shows "Some checks were not successful" right now. Following these will be beneficial to you in your career. 

So,
1. Always make sure your code at least compile before you make the pull request.
2. Follow the github test for modification.
3.  You should try your best to make your code produce the right answer. You did not mention anything about the correctness of your output, and we have to run test on our end to find that your output is incorrect. It is fine that you might not be able to get the correct answer on first try, but you must communicate that with us. Failing to do that might make people think that you did not test your code at all before uploading.

We will be here to help you fix the bug. Good luck to all of you on the finals.

2022-12-10 01:11 UTC, Summon528 requested changes
I've added some comments to the code, hopes they will help you identify and fix the bugs

2022-12-10 01:11 UTC, Summon528 commented on delete.C
> +  if (type == NULL) {
This one is probably a real bug

(⚠️ clang-diagnostic-null-arithmetic ⚠️
comparison between NULL and non-pointer (Datatype and NULL))

2022-12-10 01:11 UTC, Summon528 commented on delete.C
> +    status = attrCat->removeInfo(relation, attrName);
You might want to look into `scan.deleteRecord();`, I think `removeInfo` only remove the metadata

2022-12-10 01:11 UTC, Summon528 commented on delete.C
> +  HeapFileScan scan(attrName, status);
```suggestion
  HeapFileScan scan(relation, status);
```

2022-12-10 16:30 UTC, WalterLu3 commented on delete.C
> +    status = attrCat->removeInfo(relation, attrName);
On line 45
if (type == NULL)
I am not sure if this is the right condition to specify that we need to have an unfiltered scan in the delete case since the function input is a bit different. The DataType type actually only allows 3 values, as shown in heapfile.h 
`enum Datatype { STRING, INTEGER, FLOAT }; `
Therefore, I have done some testing and found that if no attribute is specified (i.e. all records should be deleted), the attribute type is actually a STRING. You might want to consider that when modifying your code.

2022-12-11 07:51 UTC, WalterLu3 commented
The output looks good right now. Can you do the last thing and clang-formatted delete.C as required by the github test?
You can run
`clang-format -i delete.C`
if you already have clang-format installed on your computer.

2022-12-11 20:18 UTC, Summon528 approved these changes
![SpongebobThumbsUpGIF](https://user-images.githubusercontent.com/10328757/206926697-51096b83-82ef-4ec1-a630-5e537d24b218.gif)

2022-12-11 20:26 UTC, merged